define({"Click_Link_Run_Flow":"Haga clic en este v\u00ednculo para iniciar el flujo de la muestra",
"lang_English":"English",
"Final_Page_Flow":"Esta es la \u00faltima p\u00e1gina del flujo de la muestra",
"lang_Korean":"\ud55c\uad6d\uc758",
"lang_ch":"\u4e2d\u6587",
"nls_test_sample":"This is nls test",
"lang_sp":"lengua espa\u00f1ola",
"Welcome_To_Btt_Sample":"Bienvenido a la p\u00e1gina de ejemplo BTT",
"hint_test":"This is hint test",
"pic_alt":"no pic"});