define({"IBKE2E_Need_Info":"We will need financial information from you in order to process your credit card request.  ",
"transfer":"Transfer",
"pic_alt":"no pic",
"IBKE2E_login":"login",
"length":"qwertyuiopasdfghjkl",
"Test_For_Something_symboled":"Test For {sth*}(with symbol \"*\")",
"deposit_accounts":"Deposit Accounts",
"Welcome_To_Btt_Sample":"Welcome to BTT sample page",
"IBKE2E_Missing_Info":"Missing/Incorrect Information   ",
"income_outcome_deposit":"Deposit Accounts",
"foreign_currency_accounts":"Foreign Currency",
"Title":"This title\'s name is {TitleName}",
"exit":"Exit",
"Test_For_Something":"Test For {sth}",
"last_date_of_using_internet_banking_service":"* The date of last time you used the internet banking service",
"client_level":"* Client Level",
"WTC":"Widgets Test Case",
"lang_ch":"\u4e2d\u6587",
"contact_customer_center":"Please contact customer support center at 02-729-7234,02-6322-5339",
"IBKE2E_Cancel_Confirm":"Cancel Confirmation",
"content_does_not_exist":"The content is not available yet.",
"amount":"Amount",
"IBKE2E_transaction_details":"Transaction Details",
"last_query_date_time":"Jul 9th 2012 15\:16",
"credit_card":"Credit Cards",
"father":"123",
"Text of Widget":"{property} of {WidgetName},Value is {value}",
"IBKE2E_Account_Summary":"Account  Summary",
"set property":"Set Widget Property{property}",
"IBKE2E_Congratulations":"Congratulations\!",
"shiyongnianxian":"your account from {dateFrom} to {dateTo} is a",
"group":"Group of {GoupeName}",
"note_internet_banking_service_transfer_closed":"at this situation, your internet banking service will be closed.",
"last_activity_date":"Last Activity Date",
"reset":"Reset",
"loan_accounts":"Loan Accounts",
"different_mode":"set widget property",
"client_greetings":"Hello ?",
"MTC":"Mapping Test Case",
"gold_bank":"Gold Bank",
"compare2":"This string is for comparation",
"client_level_gold":"GOLD",
"next":"Next",
"division":"Division",
"Test_For_Something_symbolpoint":"Test For {sth.}(paraName with point)",
"lang_sp":"lengua espa\u00f1ola",
"repetitivePara":"three repetitive parameters {para}{para}{para}",
"till":"and,",
"deposit_type":"Deposit Type",
"IBKE2E_Select_Cards":"Select The cards  ",
"test_widgets_properties":"Testing property {property} of widget{widget}",
"Click_Link_Run_Flow":"Click this link to launch the sample flow",
"lang_English":"English",
"DCTC":"Repetitive Parameter Test Cases",
"last_query_time":"Last Query Time",
"internet_banking_service_close_if_no_use_within_a_year":"If you do not take use of internet banking service for 1 year, ",
"client_level_benefit":"You can get special benefit with your current level.",
"insurance_contracts":"Insurance Contracts",
"half2":"I am the half2 sentence.",
"half1":"I am the half1 sentence,",
"account_number":"Account Number",
"client_name":"Clien Name",
"funds_accounts":"Funds/MMF",
"Final_Page_Flow":"This is the final page of the sample flow",
"GTC":"Grid Test Cases",
"multiselect":"multi select",
"son":"1",
"balance":"Balance",
"account_alias":"Alias Name",
"lang_Korean":"\ud55c\uad6d\uc758",
"IBKE2E_transfer":"Account Transfer",
"ETC":"ECA Test Cases",
"IBKE2E_Transfer_Confirm":"Do you confirm below money transfer?",
"IBKE2E_Account_Transfer":"Account Transfer",
"error_code_00C021":"Code\: 00C021() []",
"last_transaction_date":"Last Transaction Date",
"compare":"this string is for comparation",
"IBKE2E_Click_Run":"Click the link to run transaction",
"input":"Input\:",
"IBKE2E_Confirmation":"Confirmation",
"all_accounts_search":"All Accounts List"});