define({"stockTradingVolume":"TradingVolume",
"stockHighest":"Highest",
"stockPriceChangeRatio":"PriceChangeRatio",
"stockYesterdayClosed":"YesterdayClosed",
"buy5":"buy5",
"stockVolumeOfBusiness":"VolumeOfBusiness",
"sale5":"sale5",
"buy4":"buy4",
"stockName":"stock name",
"sale4":"sale4",
"buy3":"buy3",
"sale3":"sale3",
"buy2":"buy2",
"sale2":"sale2",
"stockOpeningPrice":"OpeningPrice",
"buy1":"buy1",
"sale1":"sale1",
"stockTheCommittee":"TheCommittee",
"stockID":"ID",
"stockChangeAmount":"ChangeAmount",
"stockBid":"Bid",
"stockTime":"Time",
"stockCompetitivePrice":"CompetitivePrice",
"stockLowest":"Lowest",
"stockNumber":"Stock number{number}",
"stockLatestPrices":"LatestPrices"});