define({"Interest":"Interest",
"Next_Step":"Next Step",
"Bill_Date":"Bill Date",
"star":"*",
"creditCardNo":"Credit Card No.",
"LastBillBalance":"Last Bill Balance",
"return":"Return",
"Acct_Status":"Account Status",
"Branch_Bank":"Branch Bank",
"Office_Phone":"Office Tel",
"Drawn_Amount":"Drawn Amount",
"Friendly_Tips":"Tips",
"Suc_Query_Points":"Query Credit Score Success\!",
"Loan_Type":"Loan Type",
"LoanAcctNo":"Loan Account No.",
"print":"Print",
"Capital_Amount":"Capital Amount",
"Welcome_To_Btt_Sample":"Welcome to BTT sample page",
"Payee_AcctNo":"Payee Account No.",
"Available_Amout":"Available Amout",
"TradeDate":"Trade Date",
"cardNo16":"At most 16 characters.",
"MinBill":"Minimum Payment",
"IDType":"ID Type",
"CurBillAlreadyPay":"Already Pay ",
"Mobile":"Mobile",
"Confirm_Drawndown_Info":"3. Confirm Drawndown Info",
"Previous_Step":"Previous Step",
"Payee_Bank":"Payee account opening bank",
"Tip_ExchangePoint":"Click here to exchange the credit points.",
"Available_Credit":"Available Credit",
"Query_Points":"Query Consumption Points",
"Dear_Customer":"Dear Customer",
"Trade_CurType":"Currency Type",
"_Month":"/Month",
"Withdrawal_Line":"Withdrawal Line",
"getIDFromMsg":"Get ID From Message",
"Short_AcctNo":"Last Four Character of the Card Number",
"Pls_Select_Acct":"1. Please select the drawdown account",
"Query_Accts":"Query Credit Account",
"Select_Acct":"1. Please Select The Draw Account.",
"PaymentDueDate":"Payment Due Date",
"Amount":"Amount",
"Drawdown_Loan":"Draw The Loan",
"Input_Drawndown_Info":"2. Please Input The Drawndown Info",
"TradeType":"Trade Type",
"Withdrawl":"Cash",
"Balance":"Balance",
"Close":"Close",
"Credit_Line":"Credit Line",
"IDNo":"ID Number",
"Home_Phone":"Home Tel",
"BookDate":"Accounts Date",
"bar":"-",
"Time_Period":"Bill Period",
"Consumption_Points":"Consumption Points",
"NewAddBill":"New Bill Of This Month",
"Drawndown_Process":"Drawndown\'s Process\:",
"Credits":"Credits",
"Click_Link_Run_Flow":"Click this link to launch the sample flow",
"MyCreditAccts":"My Credit Account",
"cardNoNull":"The Credit Card Number can not be Null.",
"Comments":"Comments",
"Validity":"Validity",
"IdentifyingCode":"Identifying Code from Message",
"Balance_Points":"Points Balance",
"Final_Page_Flow":"This is the final page of the sample flow",
"Activate_CreditCard":"Activate The Credit Card",
"download":"Download",
"OK":"OK",
"queryUnsettledBill":"Check the Unsettled Bill",
"Given_Name":"Given Name",
"Year":"Year",
"Payee_Name":"Payee\'s Name",
"Bill_CurType":"Bill\'s Currency Type",
"Opening_Bank":"Opening Bank",
"Drawndown_Success":"4. Successfully Draw",
"Confirm":"Confirm",
"Loan_Amount":"Loan Amount",
"CurBillBalance":"Current Accounting Period Balance",
"Settled_Bill":"Settled Bill",
"SignStatus":"Contract Status",
"Cur_Type":"Currency Type",
"Exchange_Point":"\"Credits Exchange\"",
"operation":"Operation",
"CurBillNeedPay":"This Period still need to pay",
"Customer_Name":"Customer Name",
"Acct_No":"Account Number",
"Reward_Points":"Reward Points",
"Unsettled_Bill":"Unsettled Bill"});